10 PRINT "BEM VINDO AO JOGO DE ADIVINHAÇÃO DE NÚMEROS!!"

30 LET NUM = INT(RAND(0, 100)*100)
40 PRINT NUM
50 PRINT "TENTE ADIVINHAR QUAL O NÚMERO!"
60 INPUT "QUAL O SEU CHUTE? "; CHUTE

70 IF CHUTE = NUM THEN PRINT "YAY!! VOCÊ ACERTOU!"
80 IF CHUTE = NUM THEN GOTO 300

100 IF CHUTE > NUM THEN PRINT "O NÚMERO QUE VOCÊ DIGITOU É MAIOR DO QUE O NÚMERO QUE TENTOU ADIVINHAR!"
120 IF CHUTE > NUM THEN GOTO 60

130 IF CHUTE < NUM THEN PRINT "O NÚMERO QUE VOCÊ DIGITOU É MENOR DO QUE O NÚMERO QUE TENTOU ADIVINHAR!"
150 IF CHUTE < NUM THEN GOTO 60

300 END